<?php
?>

<div style="text-align: center; width: 100%;">
    <div class="ib_containers">
        <img  id="image_preview_grid" class="ib_crops" src="<?php echo $this->_prepareImage('grid') ?>">
        <h4>
            <button id="ib_crop_enable">enable cropping</button>
            <?php echo Mage::helper('itembanner')->__('Grid Mode Cropping') ?>
        </h4>
    </div>
    <div class="ib_containers" id="ib_list_cropping_container">
        <img   id="image_preview_list" class="ib_crops" src="<?php echo $this->_prepareImage('list') ?>">
        <h4><?php echo Mage::helper('itembanner')->__('Grid Mode Cropping') ?></h4>
    </div>
</div>