<?php
?>
<script type="text/javascript">
    var gridAspectRatio = <?php echo Mage::getStoreConfig('cms/itembanner/grid_cropping_aspect_ratio') ?>;
    var listAspectRatio = <?php echo Mage::getStoreConfig('cms/itembanner/list_cropping_aspect_ratio') ?>;
    var gridCroppingWindow = "<?php echo Mage::helper('itembanner')->__('Crop for Grid Mode') ?>";
    var listCroppingWindow = "<?php echo Mage::helper('itembanner')->__('Crop for List Mode') ?>";
    var submitText = "<?php echo Mage::helper('itembanner')->__('Submit') ?>";
</script>
