<?php

/**
 * Created by PhpStorm.
 * User: light
 * Date: 5/28/2018
 * Time: 10:51 PM
 */
class Potoky_ViewedCommodities_Model_Lifetime extends Mage_Core_Model_Config_Data
{
    public function save()
    {
        $lifetime = $this->getValue();
        $sessCookLifetime = $lifetime = (int) Mage::getStoreConfig(Mage_Core_Model_Cookie::XML_PATH_COOKIE_LIFETIME);
        if (!preg_match('~\s*~', $lifetime)) {
            if (filter_var($lifetime, FILTER_VALIDATE_INT, array(
                "options" => array(
                    "min_range"=>0,
                    "max_range"=>$sessCookLifetime,
                ))) === false) {

                Mage::getSingleton('adminhtml/session')
                    ->addError(
                        'The value of the field either should be empty or be equal to an integer in range
                     from 0 to session coockie lifetime which now is set to: ' . $sessCookLifetime
                    );
            }
        }
        return parent::save(); // TODO: Change the autogenerated stub
    }
}