<?php
    $prodsInfoArr = Mage::helper('viewedproducts/product')
        ->getProductInfo([Mage::registry('current_product')]);
    $sku = array_keys($prodsInfoArr)[0];
    $productInfo = Mage::helper('core')->jsonEncode($prodsInfoArr[$sku]);

    $async = Mage::getStoreConfig('catalog/js_viewed_products/ajax_async');
    $lifetime = Mage::helper('viewedproducts/lifetime')->getLifetime();

    $expiry = (time() + $lifetime) * 1000;
?>
<script>
    var viewedList = storageContent(<?= $async ?>, <?= $lifetime ?>);
    if (viewedList === "[]") {
        viewedList = {};
    } else {
        viewedList = JSON.parse(viewedList);
    }
        if(viewedList.<?= $sku ?>) {
            delete viewedList.<?= $sku ?>;
        }
        viewedList.<?= $sku ?> = <?= $productInfo ?>;
        renderStorage(viewedList, <?= $expiry ?>);
    alert('In Gatherer');
</script>
