<script type="text/javascript">
    var fillData = function(e, p) {
        for (var i = 0; i < Object.keys(e).length; i++) {
            var key = Object.keys(e)[i];
            p[key] = Object.values(e)[i];
        }
    };
    var products = Object();
    var element = localStorage.getItem('viewedCommodities');
    if (element) {
        element = JSON.parse(element);
        fillData(element, products);
    } else {
        var viewedList = <?php $products = $this->getRecentlyViewedProducts();
            echo Mage::helper('viewedcommodities')->getViewedJson($products)
        ?>;
        fillData(viewedList, products);
        renderStorage("viewedCommodities", viewedList, 3600000);
    }
    var scriptTag = document.scripts[document.scripts.length - 1];
    var parentTag = scriptTag.parentNode;
    if (Object.keys(products).length !== 0) {
        document.writeln('<div class="block block-list block-viewed">');
        document.writeln('<div class="block-title">');
        document.writeln('<strong><span><?php echo $this->__('Recently Viewed Products') ?></span></strong>');
        document.writeln('</div>');
        document.writeln('<div class="block-content">');
        document.writeln('<ol id="recently-viewed-items" class="mini-products-list">');
        document.writeln('</ol>');
        (function (p) {
            for (i = 0; i < Object.keys(p).length; i++) {
                var sku = Object.keys(p)[i];
                var elemOl = document.getElementById('recently-viewed-items');
                var elemOlLi = document.createElement('li');
                elemOlLi.setAttribute('class', 'item');
                var elemOlLiA = document.createElement('a');
                elemOlLiA.setAttribute('href', p[sku].product_url);
                elemOlLiA.innerHTML = '<span class="product-image"><img src=\"' + p[sku].image_src + '\" alt=\"' + p[sku].name_link + '\"/></span>';
                var elemOlLiDiv = document.createElement('div');
                elemOlLiDiv.setAttribute('class', 'product-details');
                var elemOlLiDivP = document.createElement('p');
                elemOlLiDivP.setAttribute('class', 'product-name');
                var elemOlLiDivPA = document.createElement('a');
                elemOlLiDivPA.setAttribute('href', 'p[sku].product_url');
                elemOlLiDivPA.innerHTML = p[sku].name_link;
                elemOlLiDivP.appendChild(elemOlLiDivPA);
                elemOlLiDiv.appendChild(elemOlLiDivP);
                elemOlLi.appendChild(elemOlLiA);
                elemOlLi.appendChild(elemOlLiDiv);
                elemOl.appendChild(elemOlLi);
            }
        })(products);
        decorateList('recently-viewed-items');
        document.writeln('</div>');
        document.writeln('</div>');
    }
</script>
