<?php
    $prodsInfoArr = Mage::helper('viewedcommodities')
        ->getProductInfo([Mage::registry('current_product')]);
    $sku = array_keys($prodsInfoArr)[0];
    $productInfo = Mage::helper('core')->jsonEncode($prodsInfoArr[$sku]);
?>
<script>
    var viewedList = JSON.parse(localStorage.getItem("viewed_commodities"));
    if (viewedList) {
        //alert('in gatherer.phtml');
        viewedList.<?= $sku ?> = <?= $productInfo ?>;
        renderStorage("viewed_commodities", viewedList, 3600000);
    }
</script>