<?php
    extract(Mage::registry('viewed_commodity'));
?>
<script>
    var viewedList = localStorage.getItem("viewed_commodities");
    if (!viewedList || viewedList === "[]") {
        viewedList = {};
    } else {
        viewedList = JSON.parse(viewedList);
    }
        alert('In Gatherer fulfilling');
        viewedList.<?= $sku ?> = <?= $productInfo ?>;
        renderStorage(viewedList, 3600000);
</script>