<?php
    $prodsInfoArr = Mage::helper('viewedcommodities')
        ->getProductInfo([Mage::registry('current_product')]);
    $sku = array_keys($prodsInfoArr)[0];
    $productInfo = Mage::helper('core')->jsonEncode($prodsInfoArr[$sku]);
?>
<script>
    var viewedList = JSON.parse(localStorage.getItem("viewedCommodities"));
    if (!viewedList) {
        var responseJson = jQuery.ajax({
            url: "/viewedcommodities/storage/gather",
            type: "GET",
            async: false
        }).responseText;
        viewedList = JSON.parse(responseJson);
    } else {
        viewedList.<?= $sku ?> = <?= $productInfo ?>;
    }
    renderStorage("viewedCommodities", viewedList, 3600000);
</script>