<?php
    $product = Mage::helper('viewedcommodities')->getProductInfo([Mage::registry('current_product')]);
?>
<script>
    var viewedList = JSON.parse(localStorage.getItem("viewedCommodities"));
    if (viewedList !== null) {
        var responseJson = jQuery.ajax({
            url: "/viewedcommodities/storage/gether",
            type: "GET",
            async: false
        }).responseText;
        viewedList = JSON.parse(responseJson);
    } else {
        viewedList.$productSku = $prodInfoJson;
    }
    renderStorage("viewedCommodities", viewedList, 3600000);
</script>